sylius_grid:
    grids:
        setono_sylius_mailchimp_admin_list:
            driver:
                options:
                    class: "%setono_sylius_mailchimp.model.list.class%"
                    repository:
                        method: createListQueryBuilder
            sorting:
                config: asc
            fields:
                config:
                    type: twig
                    label: setono_sylius_mailchimp.ui.config
                    options:
                        template: "@SetonoSyliusMailchimpPlugin/Admin/Grid/Field/config.html.twig"
                listId:
                    type: string
                    label: setono_sylius_mailchimp.ui.list_id
                exportSubscribedOnly:
                    type: twig
                    label: setono_sylius_mailchimp.ui.export_subscribed_only
                    options:
                        template: "@SyliusUi/Grid/Field/yesNo.html.twig"
                storeId:
                    type: string
                    label: setono_sylius_mailchimp.ui.store_id
                storeCurrency:
                    type: twig
                    label: setono_sylius_mailchimp.ui.store_currency
                    options:
                        template: "@SetonoSyliusMailchimpPlugin/Admin/Grid/Field/currency.html.twig"
                channels:
                    type: twig
                    label: setono_sylius_mailchimp.ui.channels
                    options:
                        template: "@SetonoSyliusMailchimpPlugin/Admin/Grid/Field/collection.html.twig"
                        vars:
                            field_template: "@SetonoSyliusMailchimpPlugin/Admin/Grid/Field/channel.html.twig"
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
#                        options:
#                            link:
#                                route: setono_sylius_mailchimp_admin_list_update
                    delete:
                        type: delete
                    list_export_index:
                        type: setono_mailchimp_index
                        label: setono_sylius_mailchimp.ui.list_exports
                        options:
                            link:
                                route: setono_sylius_mailchimp_admin_list_export_index
                                parameters:
                                    mailchimpListId: resource.id
                    list_export_create:
                        type: setono_mailchimp_export
                        label: setono_sylius_mailchimp.ui.list_export
                        options:
                            link:
                                method: post
                                route: setono_sylius_mailchimp_admin_list_export_create
                                parameters:
                                    mailchimpListId: resource.id

