sylius_grid:
    grids:
        setono_sylius_mailchimp_admin_export:
            driver:
                options:
                    class: "%setono_sylius_mailchimp.model.export.class%"
                    repository:
                        method: createListQueryBuilder
            sorting:
                createdAt: desc
            fields:
                list:
                    type: twig
                    label: setono_sylius_mailchimp.ui.list
                    options:
                        template: "@SetonoSyliusMailchimpPlugin/Admin/Grid/Field/list.html.twig"
                state:
                    type: twig
                    label: setono_sylius_mailchimp.ui.state
                    sortable: ~
                    options:
                        template: "@SetonoSyliusMailchimpPlugin/Admin/Grid/Field/state.html.twig"
                        vars:
                            labels: "@SetonoSyliusMailchimpPlugin/Admin/Mailchimp/Export/Label/State"
                createdAt:
                    type: datetime
                    label: sylius.ui.created_at
                    sortable: ~
                    options:
                        format: d-m-Y H:i
                emailsExported:
                    type: string
                    label: setono_sylius_mailchimp.ui.emails_exported
                    path: customers.count
                    sortable: ~
                errorsCount:
                    type: twig
                    label: setono_sylius_mailchimp.ui.errors_count
                    path: errors
                    options:
                        template: "@SetonoSyliusMailchimpPlugin/Admin/Grid/Field/array_count.html.twig"
                finishedAt:
                    type: datetime
                    label: setono_sylius_mailchimp.ui.finished_at
                    sortable: ~
                    options:
                        format: d-m-Y H:i
            actions:
                main:
                    export:
                        type: setono_mailchimp_export
                        label: setono_sylius_mailchimp.ui.export
                        options:
                            link:
                                route: setono_sylius_mailchimp_admin_export_create
                item:
                    show:
                        type: show
                    exported_customers:
                        type: setono_mailchimp_index
                        label: setono_sylius_mailchimp.ui.exported_customers
                        options:
                            visible: resource.hasCustomers
                            link:
                                route: setono_sylius_mailchimp_admin_export_customer_index
                                parameters:
                                    mailchimpExportId: resource.id
                    restart_export:
                        type: setono_mailchimp_export_restart
                        label: setono_sylius_mailchimp.ui.export_restart
                        options:
                            visible: resource.canBeRestarted
