sylius_grid:
    templates:
        action:
            mailchimp_export: "@SetonoSyliusMailchimpPlugin/Admin/Grid/Action/export.html.twig"
    grids:
        setono_sylius_mailchimp_admin_export:
            driver:
                options:
                    class: "%setono_sylius_mailchimp.model.export.class%"
                    repository:
                        method: createListQueryBuilder
            sorting:
                createdAt: desc
            fields:
                state:
                    type: twig
                    label: setono_sylius_mailchimp.ui.state
                    options:
                        template: "@SetonoSyliusMailchimpPlugin/Admin/Grid/Field/state.html.twig"
                createdAt:
                    type: datetime
                    label: setono_sylius_mailchimp.ui.exported_at
                    sortable: ~
                    options:
                        format: d-m-Y H:i
                emails_count:
                    type: string
                    label: setono_sylius_mailchimp.ui.emails_exported
                    path: customers.count
                    sortable: ~
            actions:
                main:
                    create:
                        type: mailchimp_export
                        label: setono_sylius_mailchimp.ui.export
