setono_sylius_mailchimp_admin:
    resource: "@SetonoSyliusMailchimpPlugin/Resources/config/routing/admin.yaml"
    prefix: /admin

setono_sylius_mailchimp_shop:
    resource: "@SetonoSyliusMailchimpPlugin/Resources/config/routing/shop.yaml"
    prefix: /{_locale}
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$
