Setono\SyliusMailchimpPlugin\Model\MailchimpList:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: ['list_id']
            message: 'setono_sylius_mailchimp.list.list_id.unique'
            groups: ['setono']
    properties:
        list_id:
            - NotBlank:
                message: 'setono_sylius_mailchimp.list.list_id.not_blank'
                groups: ['setono']
            - Length:
                min: 2
                minMessage: 'setono_sylius_mailchimp.list.list_id.min_length'
                maxMessage: 'setono_sylius_mailchimp.list.list_id.max_length'
                max: 250
                groups: ['setono']
        config:
            - NotBlank:
                message: 'setono_sylius_mailchimp.list.config.not_blank'
                groups: ['setono']
