sylius_resource:
    resources:
        setono_sylius_mailchimp.export:
            driver: doctrine/orm
            classes:
                model: Setono\SyliusMailchimpPlugin\Model\MailchimpExport
                interface: Setono\SyliusMailchimpPlugin\Model\MailchimpExportInterface
                repository: Setono\SyliusMailchimpPlugin\Repository\MailchimpExportRepository
