sylius_resource:
    resources:
        setono_sylius_mailchimp.config:
            driver: doctrine/orm
            classes:
                model: Setono\SyliusMailchimpPlugin\Model\MailchimpConfig
                interface: Setono\SyliusMailchimpPlugin\Model\MailchimpConfigInterface
                form: Setono\SyliusMailchimpPlugin\Form\Type\MailchimpConfigType
                repository: Setono\SyliusMailchimpPlugin\Repository\MailchimpConfigRepository
