imports:
    - { resource: "@SetonoSyliusMailchimpPlugin/Resources/config/grids/setono_sylius_mailchimp_admin_audience.yaml" }

framework:
    messenger:
        buses:
            setono_sylius_mailchimp.command_bus: ~

sylius_grid:
    templates:
        action:
            setono_sylius_mailchimp_load_audiences: "@SetonoSyliusMailchimpPlugin/Admin/Grid/Action/load_audiences.html.twig"
            setono_sylius_mailchimp_repush_customers: "@SetonoSyliusMailchimpPlugin/Admin/Grid/Action/repush_customers.html.twig"
