imports:
    - { resource: "@SetonoSyliusMailchimpPlugin/Resources/config/grids/setono_sylius_mailchimp_admin_audience.yaml" }

framework:
    messenger:
        buses:
            setono_sylius_mailchimp.command_bus: ~
    
    workflows:
        mailchimp:
            type: 'state_machine'
            marking_store:
                type: 'method'
                property: 'mailchimpState'
            supports:
                - Setono\SyliusMailchimpPlugin\Model\MailchimpAwareInterface
            initial_marking: pending
            places:
                - pending
                - processing
                - failed
                - terminally_failed
                - pushed
            transitions:
                process:
                    from: [ pending ]
                    to: processing
                push:
                    from: processing
                    to: pushed
                fail:
                    from: [ processing ]
                    to: failed
                fail_terminally:
                    from: [ failed ]
                    to: terminally_failed
                retry:
                    from: [ failed ]
                    to: pending
                update:
                    from: [ pushed ]
                    to: pending

sylius_grid:
    templates:
        action:
            setono_sylius_mailchimp_load_audiences: "@SetonoSyliusMailchimpPlugin/Admin/Grid/Action/load_audiences.html.twig"
            setono_sylius_mailchimp_repush_customers: "@SetonoSyliusMailchimpPlugin/Admin/Grid/Action/repush_customers.html.twig"
