sylius_fixtures:
    suites:
        extra_customers:
            fixtures:
                shop_user:
                    name: "shop_user"
                    options:
                        random: 100
        default:
            fixtures:
                setono_sylius_mailchimp_config:
                    options:
                        custom:
                            mailchimp_config_default:
                                code: default
                                api_key: "%env(resolve:MAILCHIMP_API_KEY)%"
                                lists:
                                    -   name: Default list
                                        list_id: "%env(resolve:MAILCHIMP_LIST_ID)%"
                                        export_subscribed_only: false
                                        store_id: "%env(resolve:MAILCHIMP_STORE_ID)%"
                                        store_currency: USD
                                        channels:
                                            - "FASHION_WEB"
#                            mailchimp_config_no_store_configured:
#                                code: no_store
#                                api_key: "%env(resolve:MAILCHIMP_API_KEY)%"
#                                lists:
#                                    -   name: No store configured list
#                                        list_id: "%env(resolve:MAILCHIMP_LIST_ID)%"
#                                        export_subscribed_only: true
#                                        channels:
#                                            - "FASHION_WEB"
#                            mailchimp_config_no_lists:
#                                code: no_lists
#                                api_key: "%env(resolve:MAILCHIMP_API_KEY)%"
#                            mailchimp_config_invalid_api_key:
#                                code: invalid_api_key
#                                api_key: invalid
#                                lists:
#                                    -   name: Invalid API key list
#                                        list_id: "%env(resolve:MAILCHIMP_LIST_ID)%"
#                                        export_subscribed_only: true
#                                        store_id: "%env(resolve:MAILCHIMP_STORE_ID)%"
#                                        store_currency: USD
#                                        channels:
#                                            - "FASHION_WEB"
#                            mailchimp_config_invalid_store_id:
#                                code: invalid_store_id
#                                api_key: "%env(resolve:MAILCHIMP_API_KEY)%"
#                                lists:
#                                    -   name: Invalid store ID list
#                                        list_id: "%env(resolve:MAILCHIMP_LIST_ID)%"
#                                        export_subscribed_only: true
#                                        store_id: invalid
#                                        store_currency: USD
#                                        channels:
#                                            - "FASHION_WEB"
#                            mailchimp_config_invalid_list_id:
#                                code: invalid_list_id
#                                api_key: "%env(resolve:MAILCHIMP_API_KEY)%"
#                                lists:
#                                    -   name: Invalid list
#                                        list_id: invalid
#                                        export_subscribed_only: true
#                            mailchimp_config_invalid_mergefields_configured:
#                                code: invalid_mergefields_configured
#                                api_key: "%env(resolve:MAILCHIMP_API_KEY)%"
#                                lists:
#                                    -   name: Invalid mergetags configured
#                                        list_id: "%env(resolve:MAILCHIMP_LIST_ID_WITH_INVALID_MERGEFIELDS)%"
#                                        export_subscribed_only: true
#                                        store_id: "%env(resolve:MAILCHIMP_STORE_ID)%"
#                                        store_currency: USD
#                                        channels:
#                                            - "FASHION_WEB"
