imports:
    - { resource: ../grids/setono_sylius_mailchimp_admin_config.yaml }
    - { resource: ../grids/setono_sylius_mailchimp_admin_config_list.yaml }
    - { resource: ../grids/setono_sylius_mailchimp_admin_export.yaml }
    - { resource: ../grids/setono_sylius_mailchimp_admin_export_customer.yaml }
    - { resource: ../grids/setono_sylius_mailchimp_admin_list.yaml }
    - { resource: ../grids/setono_sylius_mailchimp_admin_list_export.yaml }

sylius_grid:
    templates:
        action:
            setono_mailchimp_export: "@SetonoSyliusMailchimpPlugin/Admin/Grid/Action/export.html.twig"
            setono_mailchimp_export_restart: "@SetonoSyliusMailchimpPlugin/Admin/Grid/Action/export_restart.html.twig"
            setono_mailchimp_index: "@SetonoSyliusMailchimpPlugin/Admin/Grid/Action/index.html.twig"
