winzou_state_machine:
    sylius_order_checkout:
        callbacks:
            after:
                setono_mailchimp_subscribe_customer:
                    on: ["complete"]
                    do: ["@setono_sylius_mailchimp.handler.orders_customer_subscription", "handle"]
                    args: ["object"]
                setono_mailchimp_export_order:
                    on: ["complete"]
                    do: ["@setono_sylius_mailchimp.handler.order_export", "handle"]
                    args: ["object"]
#                setono_mailchimp_cancel_order:
#                    on: "cancel"
#                    do: ["@setono_sylius_mailchimp.handler.order_remove", "handle"]
#                    args: ["object"]
