Setono\SyliusMailchimpPlugin\Model\MailchimpList:
    exclusion_policy: ALL
    xml_root_name: config
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
            groups: [Default, Detailed, Autocomplete]
        name:
            expose: true
            type: string
            groups: [Default, Detailed, Autocomplete]
    virtual_properties:
        getFullname:
            serialized_name: fullname
            groups: [Default, Detailed, Autocomplete]
