Setono\SyliusMailchimpPlugin\Model\MailchimpConfig:
    exclusion_policy: ALL
    xml_root_name: config
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
            groups: [Default, Detailed, Autocomplete]
        code:
            expose: true
            type: string
            groups: [Default, Detailed, Autocomplete]
