setono_sylius_mailchimp_admin_ajax_config:
    resource: "@SetonoSyliusMailchimpPlugin/Resources/config/routing/admin/ajax/config.yaml"
    prefix: /configs

setono_sylius_mailchimp_admin_ajax_list:
    resource: "@SetonoSyliusMailchimpPlugin/Resources/config/routing/admin/ajax/list.yaml"
    prefix: /lists
