setono_sylius_mailchimp_admin_customer:
    resource: "@SetonoSyliusMailchimpPlugin/Resources/config/routing/admin/mailchimp/customer.yaml"

setono_sylius_mailchimp_admin_export:
    resource: "@SetonoSyliusMailchimpPlugin/Resources/config/routing/admin/mailchimp/export.yaml"

setono_sylius_mailchimp_admin_list:
    resource: "@SetonoSyliusMailchimpPlugin/Resources/config/routing/admin/mailchimp/audience.yaml"
