setono_sylius_mailchimp_admin_config:
    resource: "@SetonoSyliusMailchimpPlugin/Resources/config/routing/admin/mailchimp/config.yaml"

setono_sylius_mailchimp_admin_export:
    resource: "@SetonoSyliusMailchimpPlugin/Resources/config/routing/admin/mailchimp/export.yaml"
