# setono_sylius_mailchimp_admin_config_index
# setono_sylius_mailchimp_admin_config_create
# setono_sylius_mailchimp_admin_config_update
# setono_sylius_mailchimp_admin_config_delete
setono_sylius_mailchimp_admin_config:
    resource: |
        section: admin
        alias: setono_sylius_mailchimp.config
        templates: SyliusAdminBundle:Crud
        except: ['show', 'bulkDelete']
        permission: true
        redirect: update
        grid: setono_sylius_mailchimp_admin_config
        vars:
            all:
                header: setono_sylius_mailchimp.ui.config_header
                subheader: setono_sylius_mailchimp.ui.config_subheader
                templates:
                    form: "@SetonoSyliusMailchimpPlugin/Admin/Mailchimp/Config/_form.html.twig"
    type: sylius.resource
