setono_sylius_mailchimp_admin_mailchimp_config:
    resource: |
        section: admin
        alias: setono_sylius_mailchimp.config
        templates: SetonoSyliusMailchimpPlugin:Crud
        except: ['create', 'delete']
        permission: true
        redirect: update
        vars:
            all:
                header: setono_sylius_mailchimp.ui.config_header
                subheader: setono_sylius_mailchimp.ui.config_subheader
                templates:
                    form: SetonoSyliusMailchimpPlugin:MailchimpConfig:Crud/_form.html.twig
                    breadcrumb: SetonoSyliusMailchimpPlugin:MailchimpConfig:Crud/_breadcrumb.html.twig
    type: sylius.resource
