setono_sylius_mailchimp_admin_export_index:
    path: /exports/
    methods: [GET]
    defaults:
        _controller: setono_sylius_mailchimp.controller.export:indexAction
        _sylius:
            template: SyliusAdminBundle:Crud:index.html.twig
            grid: setono_sylius_mailchimp_admin_export
            section: admin
            permission: true
            vars:
                icon: arrow up
                header: setono_sylius_mailchimp.ui.export_header
                subheader: setono_sylius_mailchimp.ui.export_subheader

setono_sylius_mailchimp_admin_export_create:
    path: /exports/new
    methods: [POST]
    defaults:
        _controller: setono_sylius_mailchimp.controller.action.export_to_mailchimp
