# setono_sylius_mailchimp_admin_list_index
# setono_sylius_mailchimp_admin_list_create
# setono_sylius_mailchimp_admin_list_update
# setono_sylius_mailchimp_admin_list_delete
setono_sylius_mailchimp_admin_list:
    resource: |
        section: admin
        alias: setono_sylius_mailchimp.list
        templates: SyliusAdminBundle:Crud
        only: ['index', 'create', 'update', 'delete']
        permission: true
        redirect: update
        grid: setono_sylius_mailchimp_admin_list
        vars:
            all:
                header: setono_sylius_mailchimp.ui.list_header
                subheader: setono_sylius_mailchimp.ui.list_subheader
            index:
                templates:
                    breadcrumb: "@SetonoSyliusMailchimpPlugin/Admin/Mailchimp/List/Index/_breadcrumb.html.twig"
            create:
                templates:
                    form: "@SetonoSyliusMailchimpPlugin/Admin/Mailchimp/List/_form.html.twig"
                    breadcrumb: "@SetonoSyliusMailchimpPlugin/Admin/Mailchimp/List/Create/_breadcrumb.html.twig"
            update:
                templates:
                    form: "@SetonoSyliusMailchimpPlugin/Admin/Mailchimp/List/_form.html.twig"
                    breadcrumb: "@SetonoSyliusMailchimpPlugin/Admin/Mailchimp/List/Update/_breadcrumb.html.twig"
    type: sylius.resource

setono_sylius_mailchimp_admin_config_list_index:
    path: /configs/{mailchimpConfigId}/lists/
    methods: [GET]
    defaults:
        _controller: setono_sylius_mailchimp.controller.list:indexAction
        _sylius:
            template: "@SyliusAdmin/Crud/index.html.twig"
            grid: setono_sylius_mailchimp_admin_config_list
            section: admin
            permission: true
            vars:
                header: setono_sylius_mailchimp.ui.list_header
                subheader: setono_sylius_mailchimp.ui.list_subheader
                route:
                    parameters:
                        mailchimpConfigId: $mailchimpConfigId
                templates:
                    form: "@SetonoSyliusMailchimpPlugin/Admin/Mailchimp/List/_form.html.twig"
                    breadcrumb: "@SetonoSyliusMailchimpPlugin/Admin/Mailchimp/Config/List/Index/_breadcrumb.html.twig"

setono_sylius_mailchimp_admin_config_list_create:
    path: /configs/{mailchimpConfigId}/lists/new
    methods: [GET, POST]
    defaults:
        _controller: setono_sylius_mailchimp.controller.list:createAction
        _sylius:
            factory:
                method: createForMailchimpConfig
                arguments:
                    - expr:notFoundOnNull(service('setono_sylius_mailchimp.repository.config').find($mailchimpConfigId))
            template: "@SyliusAdmin/Crud/create.html.twig"
            grid: setono_sylius_mailchimp_admin_config_list
            section: admin
            redirect:
                route: setono_sylius_mailchimp_admin_config_list_index
                parameters:
                    mailchimpConfigId: $mailchimpConfigId
            permission: true
            vars:
                header: setono_sylius_mailchimp.ui.config_list_header
                subheader: setono_sylius_mailchimp.ui.config_list_subheader
                route:
                    parameters:
                        mailchimpConfigId: $mailchimpConfigId
                templates:
                    form: "@SetonoSyliusMailchimpPlugin/Admin/Mailchimp/List/_form.html.twig"
                    breadcrumb: "@SetonoSyliusMailchimpPlugin/Admin/Mailchimp/Config/List/Create/_breadcrumb.html.twig"
