setono_sylius_mailchimp_admin_ajax_lists_by_phrase:
    path: /search
    methods: [GET]
    defaults:
        _controller: setono_sylius_mailchimp.controller.list:indexAction
        _format: json
        _sylius:
            serialization_groups: [Autocomplete]
            permission: true
            repository:
                method: findByPhrase
                arguments:
                    phrase: $phrase

setono_sylius_mailchimp_admin_ajax_list_by_code:
    path: /
    methods: [GET]
    defaults:
        _controller: setono_sylius_mailchimp.controller.list:indexAction
        _format: json
        _sylius:
            serialization_groups: [Autocomplete]
            permission: true
            repository:
                method: findBy
                arguments: [code: $code]
