name: CI

on: [push, pull_request]

jobs:
    composer-normalize:
        name: Composer normalize

        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@master

            -   name: Run composer normalize
                uses: docker://localheinz/composer-normalize-action:latest
    phpstan:
        name: PHPStan

        runs-on: ubuntu-latest
        
        steps:
            -   name: Checkout
                uses: actions/checkout@master
            -   name: Run phpstan analyse
                uses: docker://oskarstark/phpstan-ga
